// ==========================================================
// CATALOGUE DES INGRÉDIENTS
// Chaque ingrédient est décrit une seule fois ici, puis les
// recettes y font référence par son identifiant (ex. "oeuf").
// sprite: null = pas encore dessiné → on affiche un sprite temporaire.
// famille : pour les ranger dans l'assistant CUSTOM (voir FAMILLES).
// Sur le plateau de cuisine, on n'affiche que les ingrédients de la recette.
// ==========================================================

// Les familles d'ingrédients, dans l'ordre des boutons de l'assistant.
// Un ingrédient créé par le joueur (« + Créer ») est rangé dans l’une d’elles.
const FAMILLES = [
  { id: "legumes",   nom: "Légumes" },
  { id: "fruits",    nom: "Fruits" },
  { id: "viandes",   nom: "Viandes" },
  { id: "poissons",  nom: "Poissons" },
  { id: "laitiers",  nom: "Œufs & laitiers" },
  { id: "feculents", nom: "Féculents" },
  { id: "epices",    nom: "Épices & herbes" },
  { id: "epicerie",  nom: "Épicerie" }
];

const DOSSIER_INGREDIENTS = "assets/sprites/ingredients/";

const ingredients = {
  // ----- Légumes -----
  ail:                        { nom: "Ail",                        famille: "legumes", sprite: DOSSIER_INGREDIENTS + "ail.png" },
  artichaut:                  { nom: "Artichaut",                  famille: "legumes", sprite: DOSSIER_INGREDIENTS + "artichaut.png" },
  "asperge-blanche":          { nom: "Asperge blanche",            famille: "legumes", sprite: DOSSIER_INGREDIENTS + "asperge-blanche.png" },
  "asperge-verte":            { nom: "Asperge verte",              famille: "legumes", sprite: DOSSIER_INGREDIENTS + "asperge-verte.png" },
  aubergine:                  { nom: "Aubergine",                  famille: "legumes", sprite: DOSSIER_INGREDIENTS + "aubergine.png" },
  "aubergine-blanche":        { nom: "Aubergine blanche",          famille: "legumes", sprite: DOSSIER_INGREDIENTS + "aubergine-blanche.png" },
  "aubergine-ronde":          { nom: "Aubergine ronde",            famille: "legumes", sprite: DOSSIER_INGREDIENTS + "aubergine-ronde.png" },
  "aubergine-verte":          { nom: "Aubergine verte",            famille: "legumes", sprite: DOSSIER_INGREDIENTS + "aubergine-verte.png" },
  avocat:                     { nom: "Avocat",                     famille: "legumes", sprite: null },
  bardane:                    { nom: "Bardane",                    famille: "legumes", sprite: DOSSIER_INGREDIENTS + "bardane.png" },
  brocoli:                    { nom: "Brocoli",                    famille: "legumes", sprite: DOSSIER_INGREDIENTS + "brocoli.png" },
  butternut:                  { nom: "Butternut",                  famille: "legumes", sprite: DOSSIER_INGREDIENTS + "butternut.png" },
  carotte:                    { nom: "Carotte",                    famille: "legumes", sprite: DOSSIER_INGREDIENTS + "carotte.png" },
  "carotte-jaune":            { nom: "Carotte jaune",              famille: "legumes", sprite: DOSSIER_INGREDIENTS + "carotte-jaune.png" },
  "carotte-rouge":            { nom: "Carotte rouge",              famille: "legumes", sprite: DOSSIER_INGREDIENTS + "carotte-rouge.png" },
  "carotte-violette":         { nom: "Carotte violette",           famille: "legumes", sprite: DOSSIER_INGREDIENTS + "carotte-violette.png" },
  "celeri-rave":              { nom: "Céleri-rave",                famille: "legumes", sprite: null },
  cepe:                       { nom: "Cèpe",                       famille: "legumes", sprite: DOSSIER_INGREDIENTS + "cepe.png" },
  "champignon-brun":          { nom: "Champignon brun",            famille: "legumes", sprite: DOSSIER_INGREDIENTS + "champignon-brun.png" },
  "champignon-de-paris":      { nom: "Champignon de Paris",        famille: "legumes", sprite: DOSSIER_INGREDIENTS + "champignon-de-paris.png" },
  "champignon-noir":          { nom: "Champignon noir",            famille: "legumes", sprite: DOSSIER_INGREDIENTS + "champignon-noir.png" },
  "chou-chinois":             { nom: "Chou chinois",               famille: "legumes", sprite: DOSSIER_INGREDIENTS + "chou-chinois.png" },
  "chou-rouge":               { nom: "Chou rouge",                 famille: "legumes", sprite: DOSSIER_INGREDIENTS + "chou-rouge.png" },
  "chou-vert":                { nom: "Chou vert",                  famille: "legumes", sprite: DOSSIER_INGREDIENTS + "chou-vert.png" },
  "chou-fleur":               { nom: "Chou-fleur",                 famille: "legumes", sprite: DOSSIER_INGREDIENTS + "chou-fleur.png" },
  "chou-fleur-jaune":         { nom: "Chou-fleur jaune",           famille: "legumes", sprite: DOSSIER_INGREDIENTS + "chou-fleur-jaune.png" },
  "chou-fleur-violet":        { nom: "Chou-fleur violet",          famille: "legumes", sprite: DOSSIER_INGREDIENTS + "chou-fleur-violet.png" },
  "chou-rave":                { nom: "Chou-rave",                  famille: "legumes", sprite: DOSSIER_INGREDIENTS + "chou-rave.png" },
  "chou-rave-violet":         { nom: "Chou-rave violet",           famille: "legumes", sprite: DOSSIER_INGREDIENTS + "chou-rave-violet.png" },
  citrouille:                 { nom: "Citrouille",                 famille: "legumes", sprite: DOSSIER_INGREDIENTS + "citrouille.png" },
  concombre:                  { nom: "Concombre",                  famille: "legumes", sprite: DOSSIER_INGREDIENTS + "concombre.png" },
  "courge-cireuse":           { nom: "Courge cireuse",             famille: "legumes", sprite: DOSSIER_INGREDIENTS + "courge-cireuse.png" },
  "courge-verte":             { nom: "Courge verte",               famille: "legumes", sprite: DOSSIER_INGREDIENTS + "courge-verte.png" },
  courgette:                  { nom: "Courgette",                  famille: "legumes", sprite: DOSSIER_INGREDIENTS + "courgette.png" },
  "courgette-jaune":          { nom: "Courgette jaune",            famille: "legumes", sprite: DOSSIER_INGREDIENTS + "courgette-jaune.png" },
  cresson:                    { nom: "Cresson",                    famille: "legumes", sprite: DOSSIER_INGREDIENTS + "cresson.png" },
  "crosses-de-fougere":       { nom: "Crosses de fougère",         famille: "legumes", sprite: DOSSIER_INGREDIENTS + "crosses-de-fougere.png" },
  "daikon-rouge":             { nom: "Daikon rouge",               famille: "legumes", sprite: DOSSIER_INGREDIENTS + "daikon-rouge.png" },
  endive:                     { nom: "Endive",                     famille: "legumes", sprite: DOSSIER_INGREDIENTS + "endive.png" },
  "endive-rouge":             { nom: "Endive rouge",               famille: "legumes", sprite: DOSSIER_INGREDIENTS + "endive-rouge.png" },
  enoki:                      { nom: "Enoki",                      famille: "legumes", sprite: DOSSIER_INGREDIENTS + "enoki.png" },
  "epinard-de-malabar":       { nom: "Épinard de Malabar",         famille: "legumes", sprite: DOSSIER_INGREDIENTS + "epinard-de-malabar.png" },
  epinards:                   { nom: "Épinards",                   famille: "legumes", sprite: DOSSIER_INGREDIENTS + "epinards.png" },
  fenouil:                    { nom: "Fenouil",                    famille: "legumes", sprite: DOSSIER_INGREDIENTS + "fenouil.png" },
  girolle:                    { nom: "Girolle",                    famille: "legumes", sprite: DOSSIER_INGREDIENTS + "girolle.png" },
  gombo:                      { nom: "Gombo",                      famille: "legumes", sprite: DOSSIER_INGREDIENTS + "gombo.png" },
  "gombo-rouge":              { nom: "Gombo rouge",                famille: "legumes", sprite: DOSSIER_INGREDIENTS + "gombo-rouge.png" },
  "haricots-verts":           { nom: "Haricots verts",             famille: "legumes", sprite: DOSSIER_INGREDIENTS + "haricots-verts.png" },
  igname:                     { nom: "Igname",                     famille: "legumes", sprite: DOSSIER_INGREDIENTS + "igname.png" },
  jalapeno:                   { nom: "Jalapeño",                   famille: "legumes", sprite: null },
  komatsuna:                  { nom: "Komatsuna",                  famille: "legumes", sprite: DOSSIER_INGREDIENTS + "komatsuna.png" },
  laitue:                     { nom: "Laitue",                     famille: "legumes", sprite: DOSSIER_INGREDIENTS + "laitue.png" },
  "laitue-asperge":           { nom: "Laitue asperge",             famille: "legumes", sprite: DOSSIER_INGREDIENTS + "laitue-asperge.png" },
  "liseron-d-eau":            { nom: "Liseron d'eau",              famille: "legumes", sprite: DOSSIER_INGREDIENTS + "liseron-d-eau.png" },
  "lotus-tranches":           { nom: "Lotus en tranches",          famille: "legumes", sprite: DOSSIER_INGREDIENTS + "lotus-tranches.png" },
  mais:                       { nom: "Maïs",                       famille: "legumes", sprite: DOSSIER_INGREDIENTS + "mais.png" },
  maitake:                    { nom: "Maitake",                    famille: "legumes", sprite: DOSSIER_INGREDIENTS + "maitake.png" },
  margose:                    { nom: "Margose",                    famille: "legumes", sprite: DOSSIER_INGREDIENTS + "margose.png" },
  matsutake:                  { nom: "Matsutake",                  famille: "legumes", sprite: DOSSIER_INGREDIENTS + "matsutake.png" },
  nameko:                     { nom: "Nameko",                     famille: "legumes", sprite: DOSSIER_INGREDIENTS + "nameko.png" },
  navet:                      { nom: "Navet",                      famille: "legumes", sprite: DOSSIER_INGREDIENTS + "navet.png" },
  "navet-blanc":              { nom: "Navet blanc",                famille: "legumes", sprite: DOSSIER_INGREDIENTS + "navet-blanc.png" },
  "navet-jaune":              { nom: "Navet jaune",                famille: "legumes", sprite: DOSSIER_INGREDIENTS + "navet-jaune.png" },
  oca:                        { nom: "Oca",                        famille: "legumes", sprite: DOSSIER_INGREDIENTS + "oca.png" },
  oignon:                     { nom: "Oignon",                     famille: "legumes", sprite: DOSSIER_INGREDIENTS + "oignon.png" },
  "oignon-nouveau":           { nom: "Oignon nouveau",             famille: "legumes", sprite: null },
  "oignon-rouge":             { nom: "Oignon rouge",               famille: "legumes", sprite: DOSSIER_INGREDIENTS + "oignon-rouge.png" },
  "pak-choi":                 { nom: "Pak-choï",                   famille: "legumes", sprite: DOSSIER_INGREDIENTS + "pak-choi.png" },
  panais:                     { nom: "Panais",                     famille: "legumes", sprite: DOSSIER_INGREDIENTS + "panais.png" },
  "patate-douce":             { nom: "Patate douce",               famille: "legumes", sprite: null },
  patisson:                   { nom: "Pâtisson",                   famille: "legumes", sprite: DOSSIER_INGREDIENTS + "patisson.png" },
  "petits-pois":              { nom: "Petits pois",                famille: "legumes", sprite: DOSSIER_INGREDIENTS + "petits-pois.png" },
  "piment-jaune":             { nom: "Piment jaune",               famille: "legumes", sprite: DOSSIER_INGREDIENTS + "piment-jaune.png" },
  "piment-noir":              { nom: "Piment noir",                famille: "legumes", sprite: DOSSIER_INGREDIENTS + "piment-noir.png" },
  piment:                     { nom: "Piment rouge",               famille: "legumes", sprite: DOSSIER_INGREDIENTS + "piment.png" },
  "piment-vert":              { nom: "Piment vert",                famille: "legumes", sprite: DOSSIER_INGREDIENTS + "piment-vert.png" },
  pleurote:                   { nom: "Pleurote",                   famille: "legumes", sprite: DOSSIER_INGREDIENTS + "pleurote.png" },
  "pleurote-du-panicaut":     { nom: "Pleurote du panicaut",       famille: "legumes", sprite: DOSSIER_INGREDIENTS + "pleurote-du-panicaut.png" },
  "pois-gourmands":           { nom: "Pois gourmands",             famille: "legumes", sprite: null },
  "poivron-jaune":            { nom: "Poivron jaune",              famille: "legumes", sprite: null },
  "poivron-orange":           { nom: "Poivron orange",             famille: "legumes", sprite: DOSSIER_INGREDIENTS + "poivron-orange.png" },
  "poivron-rouge":            { nom: "Poivron rouge",              famille: "legumes", sprite: null },
  "poivron-vert":             { nom: "Poivron vert",               famille: "legumes", sprite: DOSSIER_INGREDIENTS + "poivron-vert.png" },
  "pomme-de-terre":           { nom: "Pomme de terre",             famille: "legumes", sprite: DOSSIER_INGREDIENTS + "pomme-de-terre.png" },
  "pomme-de-terre-rouge":     { nom: "Pomme de terre rouge",       famille: "legumes", sprite: DOSSIER_INGREDIENTS + "pomme-de-terre-rouge.png" },
  "pomme-de-terre-violette":  { nom: "Pomme de terre violette",    famille: "legumes", sprite: DOSSIER_INGREDIENTS + "pomme-de-terre-violette.png" },
  potiron:                    { nom: "Potiron",                    famille: "legumes", sprite: DOSSIER_INGREDIENTS + "potiron.png" },
  "pousse-de-bambou":         { nom: "Pousse de bambou",           famille: "legumes", sprite: DOSSIER_INGREDIENTS + "pousse-de-bambou.png" },
  "pousses-de-soja":          { nom: "Pousses de soja",            famille: "legumes", sprite: DOSSIER_INGREDIENTS + "pousses-de-soja.png" },
  puntarelle:                 { nom: "Puntarelle",                 famille: "legumes", sprite: DOSSIER_INGREDIENTS + "puntarelle.png" },
  "racine-de-lotus":          { nom: "Racine de lotus",            famille: "legumes", sprite: DOSSIER_INGREDIENTS + "racine-de-lotus.png" },
  radis:                      { nom: "Radis",                      famille: "legumes", sprite: DOSSIER_INGREDIENTS + "radis.png" },
  "radis-blanc":              { nom: "Radis blanc",                famille: "legumes", sprite: null },
  "radis-noir":               { nom: "Radis noir",                 famille: "legumes", sprite: DOSSIER_INGREDIENTS + "radis-noir.png" },
  "radis-pasteque":           { nom: "Radis pastèque",             famille: "legumes", sprite: DOSSIER_INGREDIENTS + "radis-pasteque.png" },
  "radis-pasteque-tranches":  { nom: "Radis pastèque en tranches", famille: "legumes", sprite: DOSSIER_INGREDIENTS + "radis-pasteque-tranches.png" },
  "radis-vert":               { nom: "Radis vert",                 famille: "legumes", sprite: DOSSIER_INGREDIENTS + "radis-vert.png" },
  rakkyo:                     { nom: "Rakkyo",                     famille: "legumes", sprite: DOSSIER_INGREDIENTS + "rakkyo.png" },
  rhubarbe:                   { nom: "Rhubarbe",                   famille: "legumes", sprite: DOSSIER_INGREDIENTS + "rhubarbe.png" },
  romaine:                    { nom: "Romaine",                    famille: "legumes", sprite: DOSSIER_INGREDIENTS + "romaine.png" },
  romanesco:                  { nom: "Romanesco",                  famille: "legumes", sprite: DOSSIER_INGREDIENTS + "romanesco.png" },
  roquette:                   { nom: "Roquette",                   famille: "legumes", sprite: DOSSIER_INGREDIENTS + "roquette.png" },
  shiitake:                   { nom: "Shiitake",                   famille: "legumes", sprite: DOSSIER_INGREDIENTS + "shiitake.png" },
  "shimeji-blanc":            { nom: "Shimeji blanc",              famille: "legumes", sprite: DOSSIER_INGREDIENTS + "shimeji-blanc.png" },
  "shimeji-brun":             { nom: "Shimeji brun",               famille: "legumes", sprite: DOSSIER_INGREDIENTS + "shimeji-brun.png" },
  taro:                       { nom: "Taro",                       famille: "legumes", sprite: DOSSIER_INGREDIENTS + "taro.png" },
  tatsoi:                     { nom: "Tatsoï",                     famille: "legumes", sprite: DOSSIER_INGREDIENTS + "tatsoi.png" },
  tomate:                     { nom: "Tomate",                     famille: "legumes", sprite: DOSSIER_INGREDIENTS + "tomate.png" },
  "tomate-allongee":          { nom: "Tomate allongée",            famille: "legumes", sprite: DOSSIER_INGREDIENTS + "tomate-allongee.png" },
  "tomate-noire":             { nom: "Tomate noire",               famille: "legumes", sprite: DOSSIER_INGREDIENTS + "tomate-noire.png" },
  "tomate-poire-jaune":       { nom: "Tomate poire jaune",         famille: "legumes", sprite: DOSSIER_INGREDIENTS + "tomate-poire-jaune.png" },
  udo:                        { nom: "Udo",                        famille: "legumes", sprite: DOSSIER_INGREDIENTS + "udo.png" },
  volvaire:                   { nom: "Volvaire",                   famille: "legumes", sprite: DOSSIER_INGREDIENTS + "volvaire.png" },

  // ----- Fruits et fruits à coque -----
  abricot:                    { nom: "Abricot",                    famille: "fruits", sprite: DOSSIER_INGREDIENTS + "abricot.png" },
  "abricot-sec":              { nom: "Abricot sec",                famille: "fruits", sprite: DOSSIER_INGREDIENTS + "abricot-sec.png" },
  amande:                     { nom: "Amande",                     famille: "fruits", sprite: DOSSIER_INGREDIENTS + "amande.png" },
  ananas:                     { nom: "Ananas",                     famille: "fruits", sprite: DOSSIER_INGREDIENTS + "ananas.png" },
  goji:                       { nom: "Baie de goji",               famille: "fruits", sprite: DOSSIER_INGREDIENTS + "goji.png" },
  "goji-seche":               { nom: "Baie de goji séchée",        famille: "fruits", sprite: DOSSIER_INGREDIENTS + "goji-seche.png" },
  banane:                     { nom: "Banane",                     famille: "fruits", sprite: DOSSIER_INGREDIENTS + "banane.png" },
  cacahuete:                  { nom: "Cacahuète",                  famille: "fruits", sprite: DOSSIER_INGREDIENTS + "cacahuete.png" },
  canneberge:                 { nom: "Canneberge",                 famille: "fruits", sprite: DOSSIER_INGREDIENTS + "canneberge.png" },
  carambole:                  { nom: "Carambole",                  famille: "fruits", sprite: DOSSIER_INGREDIENTS + "carambole.png" },
  cerise:                     { nom: "Cerise",                     famille: "fruits", sprite: DOSSIER_INGREDIENTS + "cerise.png" },
  chataigne:                  { nom: "Châtaigne",                  famille: "fruits", sprite: DOSSIER_INGREDIENTS + "chataigne.png" },
  citron:                     { nom: "Citron",                     famille: "fruits", sprite: DOSSIER_INGREDIENTS + "citron.png" },
  "citron-vert":              { nom: "Citron vert",                famille: "fruits", sprite: DOSSIER_INGREDIENTS + "citron-vert.png" },
  datte:                      { nom: "Datte",                      famille: "fruits", sprite: DOSSIER_INGREDIENTS + "datte.png" },
  "datte-fraiche":            { nom: "Datte fraîche",              famille: "fruits", sprite: DOSSIER_INGREDIENTS + "datte-fraiche.png" },
  durian:                     { nom: "Durian",                     famille: "fruits", sprite: DOSSIER_INGREDIENTS + "durian.png" },
  figue:                      { nom: "Figue",                      famille: "fruits", sprite: DOSSIER_INGREDIENTS + "figue.png" },
  "figue-blanche":            { nom: "Figue blanche",              famille: "fruits", sprite: DOSSIER_INGREDIENTS + "figue-blanche.png" },
  fraise:                     { nom: "Fraise",                     famille: "fruits", sprite: DOSSIER_INGREDIENTS + "fraise.png" },
  framboise:                  { nom: "Framboise",                  famille: "fruits", sprite: DOSSIER_INGREDIENTS + "framboise.png" },
  "fruit-de-la-passion":      { nom: "Fruit de la passion",        famille: "fruits", sprite: DOSSIER_INGREDIENTS + "fruit-de-la-passion.png" },
  grenade:                    { nom: "Grenade",                    famille: "fruits", sprite: DOSSIER_INGREDIENTS + "grenade.png" },
  jujube:                     { nom: "Jujube",                     famille: "fruits", sprite: DOSSIER_INGREDIENTS + "jujube.png" },
  "jujube-seche":             { nom: "Jujube séchée",              famille: "fruits", sprite: DOSSIER_INGREDIENTS + "jujube-seche.png" },
  kaki:                       { nom: "Kaki",                       famille: "fruits", sprite: DOSSIER_INGREDIENTS + "kaki.png" },
  kiwi:                       { nom: "Kiwi",                       famille: "fruits", sprite: DOSSIER_INGREDIENTS + "kiwi.png" },
  "main-de-bouddha":          { nom: "Main de Bouddha",            famille: "fruits", sprite: DOSSIER_INGREDIENTS + "main-de-bouddha.png" },
  mandarine:                  { nom: "Mandarine",                  famille: "fruits", sprite: DOSSIER_INGREDIENTS + "mandarine.png" },
  mangoustan:                 { nom: "Mangoustan",                 famille: "fruits", sprite: DOSSIER_INGREDIENTS + "mangoustan.png" },
  mangue:                     { nom: "Mangue",                     famille: "fruits", sprite: DOSSIER_INGREDIENTS + "mangue.png" },
  melon:                      { nom: "Melon",                      famille: "fruits", sprite: DOSSIER_INGREDIENTS + "melon.png" },
  mure:                       { nom: "Mûre",                       famille: "fruits", sprite: DOSSIER_INGREDIENTS + "mure.png" },
  myrtille:                   { nom: "Myrtille",                   famille: "fruits", sprite: DOSSIER_INGREDIENTS + "myrtille.png" },
  nashi:                      { nom: "Nashi",                      famille: "fruits", sprite: DOSSIER_INGREDIENTS + "nashi.png" },
  nefle:                      { nom: "Nèfle",                      famille: "fruits", sprite: DOSSIER_INGREDIENTS + "nefle.png" },
  noisette:                   { nom: "Noisette",                   famille: "fruits", sprite: DOSSIER_INGREDIENTS + "noisette.png" },
  noix:                       { nom: "Noix",                       famille: "fruits", sprite: DOSSIER_INGREDIENTS + "noix.png" },
  "noix-de-cajou":            { nom: "Noix de cajou",              famille: "fruits", sprite: DOSSIER_INGREDIENTS + "noix-de-cajou.png" },
  "noix-de-coco":             { nom: "Noix de coco",               famille: "fruits", sprite: DOSSIER_INGREDIENTS + "noix-de-coco.png" },
  "noix-de-macadamia":        { nom: "Noix de macadamia",          famille: "fruits", sprite: DOSSIER_INGREDIENTS + "noix-de-macadamia.png" },
  "noix-de-pecan":            { nom: "Noix de pécan",              famille: "fruits", sprite: DOSSIER_INGREDIENTS + "noix-de-pecan.png" },
  "orange-sanguine":          { nom: "Orange sanguine",            famille: "fruits", sprite: DOSSIER_INGREDIENTS + "orange-sanguine.png" },
  pamplemousse:               { nom: "Pamplemousse",               famille: "fruits", sprite: DOSSIER_INGREDIENTS + "pamplemousse.png" },
  papaye:                     { nom: "Papaye",                     famille: "fruits", sprite: DOSSIER_INGREDIENTS + "papaye.png" },
  pasteque:                   { nom: "Pastèque",                   famille: "fruits", sprite: DOSSIER_INGREDIENTS + "pasteque.png" },
  peche:                      { nom: "Pêche",                      famille: "fruits", sprite: DOSSIER_INGREDIENTS + "peche.png" },
  pistache:                   { nom: "Pistache",                   famille: "fruits", sprite: DOSSIER_INGREDIENTS + "pistache.png" },
  pitaya:                     { nom: "Pitaya",                     famille: "fruits", sprite: DOSSIER_INGREDIENTS + "pitaya.png" },
  poire:                      { nom: "Poire",                      famille: "fruits", sprite: DOSSIER_INGREDIENTS + "poire.png" },
  pomme:                      { nom: "Pomme",                      famille: "fruits", sprite: DOSSIER_INGREDIENTS + "pomme.png" },
  "pomme-verte":              { nom: "Pomme verte",                famille: "fruits", sprite: DOSSIER_INGREDIENTS + "pomme-verte.png" },
  prune:                      { nom: "Prune",                      famille: "fruits", sprite: DOSSIER_INGREDIENTS + "prune.png" },
  pruneau:                    { nom: "Pruneau",                    famille: "fruits", sprite: DOSSIER_INGREDIENTS + "pruneau.png" },
  "raisin-blanc":             { nom: "Raisin blanc",               famille: "fruits", sprite: DOSSIER_INGREDIENTS + "raisin-blanc.png" },
  "raisin-noir":              { nom: "Raisin noir",                famille: "fruits", sprite: DOSSIER_INGREDIENTS + "raisin-noir.png" },
  "raisin-rouge":             { nom: "Raisin rouge",               famille: "fruits", sprite: DOSSIER_INGREDIENTS + "raisin-rouge.png" },
  ramboutan:                  { nom: "Ramboutan",                  famille: "fruits", sprite: DOSSIER_INGREDIENTS + "ramboutan.png" },
  tamarin:                    { nom: "Tamarin",                    famille: "fruits", sprite: DOSSIER_INGREDIENTS + "tamarin.png" },
  yuzu:                       { nom: "Yuzu",                       famille: "fruits", sprite: DOSSIER_INGREDIENTS + "yuzu.png" },

  // ----- Viandes -----
  jambon:                     { nom: "Jambon",                     famille: "viandes", sprite: DOSSIER_INGREDIENTS + "jambon.png" },
  poulet:                     { nom: "Poulet",                     famille: "viandes", sprite: DOSSIER_INGREDIENTS + "poulet.png" },

  // ----- Poissons : aucun pour l'instant -----

  // ----- Œufs & laitiers -----
  aaruul:                     { nom: "Aaruul",                     famille: "laitiers", sprite: DOSSIER_INGREDIENTS + "aaruul.png" },
  beurre:                     { nom: "Beurre",                     famille: "laitiers", sprite: null },
  camembert:                  { nom: "Camembert",                  famille: "laitiers", sprite: DOSSIER_INGREDIENTS + "camembert.png" },
  cheddar:                    { nom: "Cheddar",                    famille: "laitiers", sprite: DOSSIER_INGREDIENTS + "cheddar.png" },
  "cottage-cheese":           { nom: "Cottage cheese",             famille: "laitiers", sprite: DOSSIER_INGREDIENTS + "cottage-cheese.png" },
  fromage:                    { nom: "Fromage",                    famille: "laitiers", sprite: DOSSIER_INGREDIENTS + "fromage.png" },
  "fromage-blanc":            { nom: "Fromage blanc",              famille: "laitiers", sprite: DOSSIER_INGREDIENTS + "fromage-blanc.png" },
  gouda:                      { nom: "Gouda",                      famille: "laitiers", sprite: DOSSIER_INGREDIENTS + "gouda.png" },
  lait:                       { nom: "Lait",                       famille: "laitiers", sprite: DOSSIER_INGREDIENTS + "lait.png" },
  maasdam:                    { nom: "Maasdam",                    famille: "laitiers", sprite: DOSSIER_INGREDIENTS + "maasdam.png" },
  maroilles:                  { nom: "Maroilles",                  famille: "laitiers", sprite: DOSSIER_INGREDIENTS + "maroilles.png" },
  mascarpone:                 { nom: "Mascarpone",                 famille: "laitiers", sprite: DOSSIER_INGREDIENTS + "mascarpone.png" },
  mizithra:                   { nom: "Mizithra",                   famille: "laitiers", sprite: DOSSIER_INGREDIENTS + "mizithra.png" },
  mozzarella:                 { nom: "Mozzarella",                 famille: "laitiers", sprite: DOSSIER_INGREDIENTS + "mozzarella.png" },
  "oeuf-dur":                 { nom: "Œuf dur",                    famille: "laitiers", sprite: DOSSIER_INGREDIENTS + "oeuf-dur.png" },
  oeuf:                       { nom: "Œufs",                       famille: "laitiers", sprite: DOSSIER_INGREDIENTS + "oeuf.png" },
  paneer:                     { nom: "Paneer",                     famille: "laitiers", sprite: DOSSIER_INGREDIENTS + "paneer.png" },
  parmesan:                   { nom: "Parmesan",                   famille: "laitiers", sprite: DOSSIER_INGREDIENTS + "parmesan.png" },
  qurut:                      { nom: "Qurut",                      famille: "laitiers", sprite: DOSSIER_INGREDIENTS + "qurut.png" },
  rubing:                     { nom: "Rubing",                     famille: "laitiers", sprite: DOSSIER_INGREDIENTS + "rubing.png" },
  valencay:                   { nom: "Valençay",                   famille: "laitiers", sprite: DOSSIER_INGREDIENTS + "valencay.png" },
  yaourt:                     { nom: "Yaourt",                     famille: "laitiers", sprite: DOSSIER_INGREDIENTS + "yaourt.png" },
  "yaourt-a-boire":           { nom: "Yaourt à boire",             famille: "laitiers", sprite: DOSSIER_INGREDIENTS + "yaourt-a-boire.png" },

  // ----- Féculents (céréales, légumineuses…) -----
  amarante:                   { nom: "Amarante",                   famille: "feculents", sprite: DOSSIER_INGREDIENTS + "amarante.png" },
  avoine:                     { nom: "Avoine",                     famille: "feculents", sprite: DOSSIER_INGREDIENTS + "avoine.png" },
  ble:                        { nom: "Blé",                        famille: "feculents", sprite: DOSSIER_INGREDIENTS + "ble.png" },
  feves:                      { nom: "Fèves",                      famille: "feculents", sprite: DOSSIER_INGREDIENTS + "feves.png" },
  "haricots-blancs":          { nom: "Haricots blancs",            famille: "feculents", sprite: DOSSIER_INGREDIENTS + "haricots-blancs.png" },
  "haricots-caille":          { nom: "Haricots caille",            famille: "feculents", sprite: DOSSIER_INGREDIENTS + "haricots-caille.png" },
  "haricots-carioca":         { nom: "Haricots carioca",           famille: "feculents", sprite: DOSSIER_INGREDIENTS + "haricots-carioca.png" },
  "haricots-d-espagne":       { nom: "Haricots d'Espagne",         famille: "feculents", sprite: DOSSIER_INGREDIENTS + "haricots-d-espagne.png" },
  "haricots-mungo":           { nom: "Haricots mungo",             famille: "feculents", sprite: DOSSIER_INGREDIENTS + "haricots-mungo.png" },
  "haricots-noirs":           { nom: "Haricots noirs",             famille: "feculents", sprite: DOSSIER_INGREDIENTS + "haricots-noirs.png" },
  "haricots-oeil-de-tigre":   { nom: "Haricots œil de tigre",      famille: "feculents", sprite: DOSSIER_INGREDIENTS + "haricots-oeil-de-tigre.png" },
  "haricots-rouges":          { nom: "Haricots rouges",            famille: "feculents", sprite: DOSSIER_INGREDIENTS + "haricots-rouges.png" },
  "haricots-tigres":          { nom: "Haricots tigrés",            famille: "feculents", sprite: DOSSIER_INGREDIENTS + "haricots-tigres.png" },
  "haricots-urd":             { nom: "Haricots urd",               famille: "feculents", sprite: DOSSIER_INGREDIENTS + "haricots-urd.png" },
  lentilles:                  { nom: "Lentilles",                  famille: "feculents", sprite: DOSSIER_INGREDIENTS + "lentilles.png" },
  millet:                     { nom: "Millet",                     famille: "feculents", sprite: DOSSIER_INGREDIENTS + "millet.png" },
  orge:                       { nom: "Orge",                       famille: "feculents", sprite: DOSSIER_INGREDIENTS + "orge.png" },
  "pain-de-mie":              { nom: "Pain de mie",                famille: "feculents", sprite: DOSSIER_INGREDIENTS + "pain-de-mie.png" },
  pates:                      { nom: "Pâtes",                      famille: "feculents", sprite: null },
  "pois-chiches":             { nom: "Pois chiches",               famille: "feculents", sprite: DOSSIER_INGREDIENTS + "pois-chiches.png" },
  quinoa:                     { nom: "Quinoa",                     famille: "feculents", sprite: DOSSIER_INGREDIENTS + "quinoa.png" },
  riz:                        { nom: "Riz",                        famille: "feculents", sprite: DOSSIER_INGREDIENTS + "riz.png" },
  sarrasin:                   { nom: "Sarrasin",                   famille: "feculents", sprite: DOSSIER_INGREDIENTS + "sarrasin.png" },
  seigle:                     { nom: "Seigle",                     famille: "feculents", sprite: DOSSIER_INGREDIENTS + "seigle.png" },
  soja:                       { nom: "Soja",                       famille: "feculents", sprite: DOSSIER_INGREDIENTS + "soja.png" },
  sorgho:                     { nom: "Sorgho",                     famille: "feculents", sprite: DOSSIER_INGREDIENTS + "sorgho.png" },

  // ----- Épices & herbes -----
  "ail-des-ours":             { nom: "Ail des ours",               famille: "epices", sprite: DOSSIER_INGREDIENTS + "ail-des-ours.png" },
  aneth:                      { nom: "Aneth",                      famille: "epices", sprite: DOSSIER_INGREDIENTS + "aneth.png" },
  armoise:                    { nom: "Armoise",                    famille: "epices", sprite: DOSSIER_INGREDIENTS + "armoise.png" },
  badiane:                    { nom: "Badiane",                    famille: "epices", sprite: DOSSIER_INGREDIENTS + "badiane.png" },
  basilic:                    { nom: "Basilic",                    famille: "epices", sprite: DOSSIER_INGREDIENTS + "basilic.png" },
  ciboulette:                 { nom: "Ciboulette",                 famille: "epices", sprite: DOSSIER_INGREDIENTS + "ciboulette.png" },
  "clou-de-girofle":          { nom: "Clou de girofle",            famille: "epices", sprite: DOSSIER_INGREDIENTS + "clou-de-girofle.png" },
  cumin:                      { nom: "Cumin",                      famille: "epices", sprite: DOSSIER_INGREDIENTS + "cumin.png" },
  curcuma:                    { nom: "Curcuma",                    famille: "epices", sprite: DOSSIER_INGREDIENTS + "curcuma.png" },
  gingembre:                  { nom: "Gingembre",                  famille: "epices", sprite: DOSSIER_INGREDIENTS + "gingembre.png" },
  menthe:                     { nom: "Menthe",                     famille: "epices", sprite: DOSSIER_INGREDIENTS + "menthe.png" },
  myoga:                      { nom: "Myoga",                      famille: "epices", sprite: DOSSIER_INGREDIENTS + "myoga.png" },
  muscade:                    { nom: "Noix de muscade",            famille: "epices", sprite: DOSSIER_INGREDIENTS + "muscade.png" },
  persil:                     { nom: "Persil",                     famille: "epices", sprite: DOSSIER_INGREDIENTS + "persil.png" },
  "persil-japonais":          { nom: "Persil japonais",            famille: "epices", sprite: DOSSIER_INGREDIENTS + "persil-japonais.png" },
  poivre:                     { nom: "Poivre",                     famille: "epices", sprite: DOSSIER_INGREDIENTS + "poivre.png" },
  safran:                     { nom: "Safran",                     famille: "epices", sprite: DOSSIER_INGREDIENTS + "safran.png" },
  sel:                        { nom: "Sel",                        famille: "epices", sprite: DOSSIER_INGREDIENTS + "sel.png" },
  "shiso-rouge":              { nom: "Shiso rouge",                famille: "epices", sprite: DOSSIER_INGREDIENTS + "shiso-rouge.png" },
  "shiso-vert":               { nom: "Shiso vert",                 famille: "epices", sprite: DOSSIER_INGREDIENTS + "shiso-vert.png" },
  vanille:                    { nom: "Vanille",                    famille: "epices", sprite: DOSSIER_INGREDIENTS + "vanille.png" },

  // ----- Épicerie -----
  eau:                        { nom: "Eau",                        famille: "epicerie", sprite: DOSSIER_INGREDIENTS + "eau.png" },
  "eau-gazeuse":              { nom: "Eau gazeuse",                famille: "epicerie", sprite: DOSSIER_INGREDIENTS + "eau-gazeuse.png" },
  farine:                     { nom: "Farine",                     famille: "epicerie", sprite: null },
  "graines-de-chia":          { nom: "Graines de chia",            famille: "epicerie", sprite: DOSSIER_INGREDIENTS + "graines-de-chia.png" },
  hijiki:                     { nom: "Hijiki",                     famille: "epicerie", sprite: DOSSIER_INGREDIENTS + "hijiki.png" },
  huile:                      { nom: "Huile",                      famille: "epicerie", sprite: null },
  kelp:                       { nom: "Kelp",                       famille: "epicerie", sprite: DOSSIER_INGREDIENTS + "kelp.png" },
  kombu:                      { nom: "Kombu",                      famille: "epicerie", sprite: DOSSIER_INGREDIENTS + "kombu.png" },
  "levure-chimique":          { nom: "Levure chimique",            famille: "epicerie", sprite: null },
  nori:                       { nom: "Nori",                       famille: "epicerie", sprite: DOSSIER_INGREDIENTS + "nori.png" },
  "pepites-chocolat":         { nom: "Pépites de chocolat",        famille: "epicerie", sprite: DOSSIER_INGREDIENTS + "pepites-chocolat.png" },
  sucre:                      { nom: "Sucre",                      famille: "epicerie", sprite: null },
  wakame:                     { nom: "Wakame",                     famille: "epicerie", sprite: DOSSIER_INGREDIENTS + "wakame.png" }
};

// CATALOGUE DES USTENSILES ET DE L'ÉLECTROMÉNAGER
// Même principe que les ingrédients : les recettes y font référence par
// leur identifiant. Ils servent à la liste de l'écran de préparation,
// au centre de l'écran de cuisine, et à l'assistant CUSTOM.
// groupe : pour les ranger dans le sous-menu de l'assistant (voir GROUPES_USTENSILES).

const GROUPES_USTENSILES = [
  { id: "cuisson",        nom: "Poêles & casseroles" },
  { id: "plats",          nom: "Plats & moules" },
  { id: "bols",           nom: "Bols & mesures" },
  { id: "outils",         nom: "Petits outils" },
  { id: "electromenager", nom: "Électroménager" }
];

const DOSSIER_USTENSILES = "assets/sprites/ustensiles/";

const ustensiles = {
  // ----- Poêles & casseroles -----
  casserole:        { nom: "Casserole",            groupe: "cuisson", sprite: null },
  cocotte:          { nom: "Cocotte",              groupe: "cuisson", sprite: null },
  faitout:          { nom: "Faitout",              groupe: "cuisson", sprite: null },
  poele:            { nom: "Poêle",                groupe: "cuisson", sprite: null },
  sauteuse:         { nom: "Sauteuse",             groupe: "cuisson", sprite: null },
  wok:              { nom: "Wok",                  groupe: "cuisson", sprite: null },

  // ----- Plats & moules -----
  moule:            { nom: "Moule",                groupe: "plats", sprite: null },
  "moule-gateau":   { nom: "Moule à gâteau",       groupe: "plats", sprite: null },
  "moule-muffins":  { nom: "Moule à muffins",      groupe: "plats", sprite: null },
  "moule-tarte":    { nom: "Moule à tarte",        groupe: "plats", sprite: null },
  "plat-gratin":    { nom: "Plat à gratin",        groupe: "plats", sprite: null },
  plaque:           { nom: "Plaque de four",       groupe: "plats", sprite: null },
  ramequin:         { nom: "Ramequin",             groupe: "plats", sprite: null },

  // ----- Bols & mesures -----
  assiette:         { nom: "Assiette",             groupe: "bols", sprite: DOSSIER_USTENSILES + "assiette.png" },
  balance:          { nom: "Balance de cuisine",   groupe: "bols", sprite: null },
  bol:              { nom: "Bol",                  groupe: "bols", sprite: DOSSIER_USTENSILES + "bol.png" },
  saladier:         { nom: "Saladier",             groupe: "bols", sprite: null },
  "verre-mesureur": { nom: "Verre mesureur",       groupe: "bols", sprite: null },

  // ----- Petits outils -----
  ciseaux:          { nom: "Ciseaux",              groupe: "outils", sprite: null },
  couteau:          { nom: "Couteau",              groupe: "outils", sprite: null },
  cuillere:         { nom: "Cuillère en bois",     groupe: "outils", sprite: null },
  econome:          { nom: "Économe",              groupe: "outils", sprite: null },
  ecumoire:         { nom: "Écumoire",             groupe: "outils", sprite: null },
  fouet:            { nom: "Fouet",                groupe: "outils", sprite: null },
  fourchette:       { nom: "Fourchette",           groupe: "outils", sprite: null },
  louche:           { nom: "Louche",               groupe: "outils", sprite: null },
  maryse:           { nom: "Maryse",               groupe: "outils", sprite: null },
  "ouvre-boite":    { nom: "Ouvre-boîte",          groupe: "outils", sprite: null },
  "papier-cuisson": { nom: "Papier cuisson",       groupe: "outils", sprite: null },
  passoire:         { nom: "Passoire",             groupe: "outils", sprite: null },
  pince:            { nom: "Pince",                groupe: "outils", sprite: null },
  pinceau:          { nom: "Pinceau",              groupe: "outils", sprite: null },
  planche:          { nom: "Planche à découper",   groupe: "outils", sprite: null },
  "presse-ail":     { nom: "Presse-ail",           groupe: "outils", sprite: null },
  rape:             { nom: "Râpe",                 groupe: "outils", sprite: null },
  rouleau:          { nom: "Rouleau à pâtisserie", groupe: "outils", sprite: null },
  spatule:          { nom: "Spatule",              groupe: "outils", sprite: null },
  tamis:            { nom: "Tamis",                groupe: "outils", sprite: null },

  // ----- Électroménager -----
  airfryer:         { nom: "Airfryer",             groupe: "electromenager", sprite: null },
  raclette:         { nom: "Appareil à raclette",  groupe: "electromenager", sprite: null },
  batteur:          { nom: "Batteur",              groupe: "electromenager", sprite: null },
  blender:          { nom: "Blender",              groupe: "electromenager", sprite: null },
  bouilloire:       { nom: "Bouilloire",           groupe: "electromenager", sprite: null },
  cookeo:           { nom: "Cookeo (autocuiseur)", groupe: "electromenager", sprite: null },
  congelateur:      { nom: "Congélateur",          groupe: "electromenager", sprite: null },
  "cuiseur-riz":    { nom: "Cuiseur à riz",        groupe: "electromenager", sprite: null },
  four:             { nom: "Four",                 groupe: "electromenager", sprite: null },
  gaufrier:         { nom: "Gaufrier",             groupe: "electromenager", sprite: null },
  "grille-pain":    { nom: "Grille-pain",          groupe: "electromenager", sprite: null },
  microondes:       { nom: "Micro-ondes",          groupe: "electromenager", sprite: null },
  mixeur:           { nom: "Mixeur",               groupe: "electromenager", sprite: null },
  "mixeur-plongeant": { nom: "Mixeur plongeant",   groupe: "electromenager", sprite: null },
  "plaque-cuisson": { nom: "Plaque de cuisson",    groupe: "electromenager", sprite: null },
  refrigerateur:    { nom: "Réfrigérateur",        groupe: "electromenager", sprite: null },
  robot:            { nom: "Robot pâtissier",      groupe: "electromenager", sprite: null }
};
